server:
  port: 8080
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: profesor-service
          uri: lb://profesor-service
          predicates:
            - Path=/profesores/**
        - id: prestamo-service
          uri: lb://prestamo-service
          predicates:
            - Path=/prestamos/**
        - id: proyector-service
          uri: lb://proyector-service
          predicates:
            - Path=/proyectores/**
        - id: devolucion-service
          uri: lb://devolucion-service
          predicates:
            - Path=/devoluciones/**
        